language: python
python:
  - "3.7"
services:
- postgresql
install:
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
script:
- "./ci/set_version_from_git_tag.sh"
- "./ci/lint.sh"
- "./ci/unit_test.sh"
- "./ci/integration_test.sh"
after_success:
- coveralls
deploy:
  skip_cleanup: true
  provider: pypi
  username: __token__
  password:
    secure: El5CQgORyY6+2e7+pHc2FZbcaZpgz6al7hXxOfjhjsoH0scgva/gawQjdEqOCZvVX8UrnRj+zS2/Nw1xRISjjy/wLlMBR7mT3eA/KzrUOL32MawXmJ5l415Y0LJl87nQw19odCGhaEKCTo8W9dScPSlX2AqIInTJCxrW9KyWtrB1lEp/7i8ISbww/WX4xfoqVnkvZmbELrxmNZxlmZZCC4wQYubhNz4SQFbe8VgGrBCSVlJ7madfB3Ivvf9hd5h/3UHolm6/YaXoRCxYXufdPO6eCEjdRgJclMxZr3OlxiauoU9dPUy8rfpn9Zio1kDXzh/E3IteEiNC0hL9cAn01orM6SgioYbxZixaiBhlOaTzEoBANOionaAzN4si2w06NEnuARwtzmvZWED+TadjrP3Lrqb4gcGpAOUDjobLd2GnTE3iNTuy3DN52uDWn/1UASwAaVqi+5+Ck9F2dQjkTq5rct7sMPtndZ7lITWLgq7AQezIKIMTit1p/rXdSDjdLP2KDBSiPhp1bFIRuivgXRHPDLFW3jWYhIyVItqojete3rhpLal9oSlkFUQM6uC/x+7iqYllYvBApgVUyq/QBA7UOmVGzqrZoqSsMDoc9oCer2h1WV7Y6y5Csww2LXWzyxpTcsBK2FihoYJC97yntHMPgdTP1ga3YV+8mSxqq8s=
  on:
    tags: true
  distributions: sdist bdist_wheel
