language: python

services:
  - postgresql

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

before_script:
  - ./ci/setup_db.sh

script:
  - ./ci/lint.sh
  - ./ci/test.sh

after_success:
  - coveralls
