language: python
services:
- postgresql
install:
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
script:
- "./ci/set_version_from_git_tag.sh"
- "./ci/lint.sh"
- "./ci/unit_test.sh"
- "./ci/integration_test.sh"
after_success:
- coveralls
deploy:
  skip_cleanup: true
  provider: pypi
  username: __token__
  password:
    secure: CaMqwxYZda5s+bIzOJMr5EJ0ykBF/I7Qjy+FsiG8lpkHblTPGApT75Nf/8w7+r1fonmQEn1l3z/jXKkIVwtKd9nYqDmTYD6FMg6aHGHT6j/jbmgEbCOFqfP0KrbW4b1MjYjSpo9L47iDsEoH6/9Oe/rv9sh+DWs/UIexqr8mpNhufwMhIqdsg3OqtuonCzZGBPB6yzTBEJuOuv+MarPdUPPAxa6T6kSpET41oGOLYnaXmuyA3ZBYFxNBV03wh+6h3wx8nD2XfF1n0uHAD84uOY8meZP8QkAGZWnDYCUYdzln7sKwjJDWopWdWckNX9Ik2z28uUYWrw2pwzbUB3F6/3Hw02Y20NdRH5wDcxlpQVzaXuvgfdCIs5bALTcj9c2zg39MxaoOPmLduci9d5K6oEIZf4H8aZusvcTE5pLSMuAj35uZqLO1H55oCrEevTiZuPSVf/2vXMhLWmaqLUIfubP+nMLIMXKMW8kRm1TjOwFuSihKfwsPghcp21U4tUrdRjyt6IEIaGk3bi2Oqf9nR9Ee+WAgmBkhmWSMJ8Dd3iotVRAvyMuqm9NSf7HfTrxv0q4x/3AHkJ8dTBaLuBeJ0+Jz19df+uZCOxTFZHIDdUqdZbDsMAyyiA9wdggl/+fqPpQGab0uspG3cPpMaQKiMHq0kOBX8/sQWPPJWRwvdGA=
  on:
    tags: true
  distributions: sdist bdist_wheel
