language: python

services:
  - postgresql

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  - ./ci/lint.sh
  - ./ci/unit_test.sh
  - ./ci/integration_test.sh

after_success:
  - coveralls
